const genreMapping = [
    { 1: "Action" },
    { 2: "Adventure" },
    { 3: "Chuyển sinh" },
    { 4: "Cooking" },
    { 5: "Comedy" },
    { 6: "Comic" },
    { 7: "Cổ đại" },
    { 8: "Drama" },
    { 9: "Historical" },
    { 10: "Horror" },
    { 11: "Live action" },
    { 12: "Manga" },
    { 13: "Manhua" },
    { 14: "Manhwa" },
    { 15: "Psylogical" },
    { 16: "Romance" },
    { 17: "School Life" },
    { 18: "Sci-fi" },
    { 19: "Sports" },
    { 20: "Thiếu nhi" },
    { 21: "Trinh thám" },
    { 22: "Truyện scan" },
    { 23: "Truyện màu" },
  ];
module.exports = genreMapping;